config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "pwa#manifest", as: :pwa_manifest
  get "service-worker" => "pwa#service_worker", as: :pwa_service_worker
  get "offline" => "pwa#offline"

  # Defines the root path route ("/")
  root "home#home", defaults: { sw_offline_cache: true }

  get "offline-cached" => "home#offline_cached", defaults: { sw_offline_cache: true }
  get "warm-cached" => "home#warm_cached", defaults: { sw_warm_cache: true }
  get "online-only-with-fallback" => "home#online_only_with_fallback"
  get "online-only" => "home#online_only", defaults: { sw_no_fallback: true }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def offline_cached
  end

  def warm_cached
  end

  def online_only
  end

  def online_only_with_fallback
  end
end

app/controllers/pwa_controller.rb
# The Rails::PwaController is not used since we need to disable CSP for the service worker
# since Google Workbox SW is imported from a CDN and `offline` action has been added
# https://github.com/rails/rails/pull/54657
class PwaController < ActionController::Base
  skip_forgery_protection
  layout "application", only: :offline

  def manifest; end

  def service_worker
    @offline_cached_paths = Rails.application.config.service_worker.offline_cached_paths
    @warm_cached_paths = Rails.application.config.service_worker.warm_cached_paths
    @no_fallback_paths = Rails.application.config.service_worker.no_fallback_paths
  end

  def offline; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_menu_class(path)
    "text-gray-500" if current_page?(path)
  end
end

app/views/home/home.html.erb
<main class="container mx-auto mt-18 px-5">
  <div class="flex mb-4 mt-6">
    <%= render 'shared/navigation' %>

    <div class="flex-1 min-w-60 text-center"">
      <h1>Home 🏡</h1>
      <p class="ml-auto mr-auto max-w-140">
        This is a simple Ruby on Rails app showing how a service worker can be used
        to cache pages and display them offline using
        <a href="https://developer.chrome.com/docs/workbox" target="_blank">Google Workbox</a>
      </p>
      <p class="mt-6 ml-auto mr-auto max-w-140">
        If you disconnect from the internet, you should see different offline behaviours
        when clicking the left hand menu items
      </p>
      <p class="mt-6 ml-auto mr-auto max-w-140">
        To see what's happening under the hood <a href="https://developer.chrome.com/docs/workbox" target="_blank">Google Workbox</a>
        logging is output in Chrome's developer console
      </p>
      <p class="mt-6 ml-auto mr-auto max-w-140">
        <a href="https://github.com/jpawlyn/offline-demo-app?tab=readme-ov-file#offline-demo-app" target="_blank">Source code</a>
    </div>
  </div>
</main>

app/views/home/offline_cached.html.erb
<main class="container mx-auto mt-18 px-5">
  <div class="flex mb-4 mt-6">
    <%= render 'shared/navigation' %>

    <div class="flex-1 min-w-60 text-center"">
      <h1>Offline cached 🛟</h1>
      <p class="ml-auto mr-auto max-w-140">
        This page is cached for offline viewing but only once it has been accessed online
      </p>
      <p class="mt-6 ml-auto mr-auto max-w-140">
        If it is viewed offline before being accessed online, the fallback page is shown
      </p>
      <p class="mt-6 ml-auto mr-auto max-w-140">
        This is done using Google Workbox's
        <a href="https://developer.chrome.com/docs/workbox/modules/workbox-strategies#network_first_network_falling_back_to_cache" target="_blank">
          network first strategy
        </a>
      </p>
    </div>
  </div>
</main>

app/views/home/online_only.html.erb
<main class="container mx-auto mt-18 px-5">
  <div class="flex mb-4 mt-6">
    <%= render 'shared/navigation' %>

    <div class="flex-1 min-w-60 text-center">
      <h1>Online only 🛜</h1>
      <p class="ml-auto mr-auto max-w-140">
        This page is never cached and has no offline fallback
      </p>
      <p class="mt-6 ml-auto mr-auto max-w-140">
        This is done by excluding the page from all service worker route registrations
      </p>
    </div>
  </div>
</main>

app/views/home/online_only_with_fallback.html.erb
<main class="container mx-auto mt-18 px-5">
  <div class="flex mb-4 mt-6">
    <%= render 'shared/navigation' %>

    <div class="flex-1 min-w-60 text-center">
      <h1>Online only with fallback 🛜</h1>
      <p class="ml-auto mr-auto max-w-140">
        This page is never cached and shows a fallback when offline
      </p>
      <p class="mt-6 ml-auto mr-auto max-w-140">
        This is done using Google Workbox's
        <a href="https://developer.chrome.com/docs/workbox/modules/workbox-strategies#network_only" target="_blank">
          network only strategy
        </a> in combination with
        <a href="https://developer.chrome.com/docs/workbox/modules/workbox-routing#set_a_catch_handler" target="_blank">
          setting a catch handler
        </a>
      </p>
    </div>
  </div>
</main>

app/views/home/warm_cached.html.erb
<main class="container mx-auto mt-18 px-5">
  <div class="flex mb-4 mt-6">
    <%= render 'shared/navigation' %>

    <div class="flex-1 min-w-60 text-center">
      <h1>Warm cached ☀️</h1>
      <p class="ml-auto mr-auto max-w-140">
        This page is cached as soon as the service worker is installed and
        even if it is never accessed online, it can always be viewed offline
      </p>
      <p class="mt-6 ml-auto mr-auto max-w-140">
        This is done using Google Workbox's
        <a href="https://developer.chrome.com/docs/workbox/modules/workbox-recipes#warm_strategy_cache" target="_blank">
          warm strategy recipe
        </>
      </p>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Offline Demo App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navigation.html.erb
<div class="flex-initial w-50 mt-8">
  <p><%= link_to 'Home', root_path, class: active_menu_class(root_path) %></p>
  <p class="mt-1"><%= link_to 'Warm cached', warm_cached_path, class: active_menu_class(warm_cached_path) %></p>
  <p class="mt-1"><%= link_to 'Offline cached', offline_cached_path, class: active_menu_class(offline_cached_path) %></p>
  <p class="mt-1"><%= link_to 'Online only with fallback', online_only_with_fallback_path, class: active_menu_class(online_only_with_fallback_path) %></p>
  <p class="mt-1"><%= link_to 'Online only', online_only_path, class: active_menu_class(online_only_path) %></p>
</div>